# Generated by Django 5.2.17 on 2026-08-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('question', models.CharField(max_length=300, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
            ],
            options={
                'verbose_name': '常见问题',
                'verbose_name_plural': '常见问题',
            },
        ),
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('slug', models.SlugField(unique=True, verbose_name='标识')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='正文')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='分类')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('links', models.JSONField(blank=True, default=list, verbose_name='参考链接')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学习日志',
                'verbose_name_plural': '学习日志',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('slug', models.SlugField(unique=True, verbose_name='标识')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='价格')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='图片')),
                ('external_url', models.URLField(blank=True, verbose_name='外部链接')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('slug', models.SlugField(unique=True, verbose_name='标识')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='分类')),
                ('resource_type', models.CharField(default='download', max_length=30, verbose_name='类型')),
                ('download_url', models.URLField(blank=True, verbose_name='下载链接')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('extract_code', models.CharField(blank=True, max_length=50, verbose_name='提取码')),
                ('archive_password', models.CharField(blank=True, max_length=100, verbose_name='解压密码')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资料资源',
                'verbose_name_plural': '资料资源',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('slug', models.SlugField(unique=True, verbose_name='标识')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('thumbnail', models.CharField(blank=True, max_length=500, verbose_name='缩略图')),
                ('duration', models.CharField(blank=True, max_length=30, verbose_name='时长')),
                ('published_at', models.CharField(blank=True, max_length=30, verbose_name='发布日期')),
                ('bvid', models.CharField(blank=True, max_length=50, verbose_name='BVID')),
            ],
            options={
                'verbose_name': '教学视频',
                'verbose_name_plural': '教学视频',
            },
        ),
    ]
