# Generated by Django 5.2.17 on 2026-08-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['sort_order', '-pk'], 'verbose_name': '常见问题', 'verbose_name_plural': '常见问题'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', '-pk'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['sort_order', '-pk'], 'verbose_name': '资料资源', 'verbose_name_plural': '资料资源'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['sort_order', '-pk'], 'verbose_name': '教学视频', 'verbose_name_plural': '教学视频'},
        ),
    ]
